import {Project, SourceFile} from "ts-morph";
import {ComponentData} from "./types.js";
import path from "path";
import fs from "fs/promises";
import {Logger} from "./utils.js";
import {ObjectSchema} from "@reactive-forge/schema";

const generatedMarker = "// Generated by reactive-forge codegen. Do not edit."

async function saveFileIfChanged(file: SourceFile, logger: Logger): Promise<void> {
    try {
        if (await fs.readFile(file.getFilePath(), "utf-8") === file.getFullText()) return
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
    }

    logger.info(`Updating ${file.getFilePath()}`)
    await fs.mkdir(path.dirname(file.getFilePath()), { recursive: true })
    await file.save()
}

function isInside(directory: string, file: string): boolean {
    const relative = path.relative(directory, file)
    return relative !== "" && relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)
}

async function assertGeneratedTarget(project: Project, target: string, sourcePaths: Set<string>): Promise<void> {
    if (sourcePaths.has(target)) throw new Error(`Generated file would overwrite component source: ${target}`)

    let existing: string | undefined
    try {
        existing = await fs.readFile(target, "utf-8")
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
    }
    existing ??= project.getSourceFile(target)?.getFullText()
    if (existing !== undefined && !existing.startsWith(generatedMarker))
        throw new Error(`Refusing to overwrite a file not generated by reactive-forge: ${target}`)
}

export interface GenerateConfig {
    outDir: string
    rootDir: string
    baseDir: string
    pathPrefix: string
}

export async function generateFiles(project: Project, components: ComponentData[], { outDir, rootDir, baseDir, pathPrefix }: GenerateConfig, logger: Logger) {
    interface FileRecord {
        sourcePath: string
        targetPath: string
        specifier: string
        filePath: string
        components: ComponentData[]
    }

    const outputRoot = path.resolve(outDir)
    const sourceRoot = path.resolve(rootDir)
    const records = new Map<string, FileRecord>()

    for (const component of components) {
        const sourcePath = path.resolve(component.sourcePath)
        if (!isInside(sourceRoot, sourcePath))
            throw new Error(`Component source is outside rootDir: ${sourcePath}`)

        let record = records.get(sourcePath)
        if (record === undefined) {
            const relativeSource = path.relative(sourceRoot, sourcePath)
            const targetPath = path.resolve(outputRoot, "__reactive_forge_files", `${relativeSource}.ts`)
            if (!isInside(outputRoot, targetPath))
                throw new Error(`Generated file would escape outDir: ${targetPath}`)

            const relativeImport = path.relative(path.dirname(targetPath), sourcePath).replace(/\.(tsx?|jsx?)$/i, "").replace(/\\/g, "/")
            const specifier = relativeImport.startsWith(".") ? relativeImport : `./${relativeImport}`
            const filePath = path.relative(path.resolve(baseDir), sourcePath).replace(/\.(tsx?|jsx?)$/i, "").replace(/\\/g, "/")
            record = { sourcePath, targetPath, specifier, filePath, components: [] }
            records.set(sourcePath, record)
        }
        record.components.push(component)
    }

    const modules = [...records.values()].sort((a, b) => a.sourcePath.localeCompare(b.sourcePath))
    const aggregatePath = path.resolve(outputRoot, "index.ts")
    const sourcePaths = new Set(modules.map(module => module.sourcePath))
    for (const target of [...modules.map(module => module.targetPath), aggregatePath])
        await assertGeneratedTarget(project, target, sourcePaths)

    const outputFiles: SourceFile[] = []
    for (const module of modules) {
        const resultFile = project.createSourceFile(module.targetPath, "", { overwrite: true })
        resultFile.addImportDeclaration({
            moduleSpecifier: "react",
            namedImports: [{ name: "FC", isTypeOnly: true }]
        })
        resultFile.addImportDeclaration({
            moduleSpecifier: "@reactive-forge/schema",
            namedImports: [{ name: "ComponentFileData", isTypeOnly: true }]
        })

        const imports = module.components.map((component, index) => ({ component, localName: `_rf_component_${String(index)}` }))
        for (const { component, localName } of imports) {
            resultFile.addImportDeclaration({
                moduleSpecifier: module.specifier,
                ...(component.isDefault
                    ? { defaultImport: localName }
                    : { namedImports: [{ name: /^[A-Za-z_$][\w$]*$/.test(component.name) ? component.name : JSON.stringify(component.name), alias: localName }] })
            })
        }

        const componentEntries = imports.map(({ component, localName }) => {
            const argsJson = JSON.stringify(new ObjectSchema(component.args).toJson())
            return `\t\t[${JSON.stringify(component.name)}]: {\n\t\t\tcomponent: ${localName} as FC,\n\t\t\targs: ${argsJson}\n\t\t}`
        }).join(",\n")

        resultFile.addStatements(
            `export const __file: ComponentFileData = {\n\tpath: ${JSON.stringify(pathPrefix + module.filePath)},\n\tcomponents: {\n${componentEntries}\n\t}\n}`
        )
        resultFile.formatText()
        resultFile.insertText(0, `${generatedMarker}\n`)
        outputFiles.push(resultFile)
    }

    const aggregateFile = project.createSourceFile(aggregatePath, "", { overwrite: true })
    aggregateFile.addImportDeclaration({
        moduleSpecifier: "@reactive-forge/schema",
        namedImports: [{ name: "ComponentLibraryData", isTypeOnly: true }]
    })

    const libraryFiles = modules.map((module, index) => {
        const relativePath = path.relative(outputRoot, module.targetPath).replace(/\.ts$/, ".js").replace(/\\/g, "/")
        const alias = `_rf_file_${String(index)}`
        aggregateFile.addImportDeclaration({
            moduleSpecifier: `./${relativePath}`,
            namedImports: [{ name: "__file", alias }]
        })
        return alias
    })
    aggregateFile.addStatements(
        `export const components: ComponentLibraryData = {\n\tfiles: [\n${libraryFiles.map(file => `\t\t${file}`).join(",\n")}\n\t]\n}`
    )
    aggregateFile.formatText()
    aggregateFile.insertText(0, `${generatedMarker}\n`)
    outputFiles.push(aggregateFile)

    for (const file of outputFiles) await saveFileIfChanged(file, logger)
}
