import {Project, SourceFile} from "ts-morph";
import {ComponentData} from "./types.js";
import path from "path";
import fs from "fs/promises";
import {Logger} from "./utils.js";
import {exampleValue, ObjectSchema} from "@reactive-forge/schema";
import {shortHash} from "./hash.js";
import {ComponentMetadata, Diagnostic, MetadataDocument, PropMetadata} from "./metadataTypes.js";

const generatedMarker = "// Generated by reactive-forge codegen. Do not edit."

// Filename for the portable metadata artifact (docs/metadata-contract.md).
// Not specified by the contract or handoff; "metadata.json" is chosen for
// discoverability next to the generated `index.ts` registry it describes.
const metadataFileName = "metadata.json"

function buildMetadataDocument(components: ComponentData[], rootDir: string): MetadataDocument {
    const rootPath = path.resolve(rootDir)

    const metaComponents: ComponentMetadata[] = components.map(component => {
        const relativeSourcePath = path.relative(rootPath, path.resolve(component.sourcePath)).replace(/\\/g, "/")
        const id = shortHash(`${relativeSourcePath}\u0000${component.name}`)

        const props: Record<string, PropMetadata> = {}
        for (const [propName, propSchema] of Object.entries(component.args)) {
            const meta = component.propMeta[propName]
            const example = exampleValue(propSchema.schema)
            props[propName] = {
                schema: propSchema.schema.toJson(),
                required: propSchema.required,
                ...(meta?.description !== undefined ? { description: meta.description } : {}),
                ...(meta?.defaultValue !== undefined ? { defaultValue: meta.defaultValue } : {}),
                ...(example !== undefined ? { exampleValue: example } : {}),
                diagnostics: meta?.diagnostics ?? []
            }
        }

        return {
            id,
            name: component.name,
            sourcePath: relativeSourcePath,
            isDefault: component.isDefault,
            ...(component.description !== undefined ? { description: component.description } : {}),
            props,
            diagnostics: component.diagnostics
        }
    })

    return {
        schemaVersion: 1,
        generatedAt: new Date().toISOString(),
        components: metaComponents
    }
}

function countDiagnostics(document: MetadataDocument): { errors: number, warnings: number } {
    let errors = 0
    let warnings = 0
    const tally = (diagnostics: Diagnostic[]) => {
        for (const diagnostic of diagnostics) {
            if (diagnostic.severity === "error") errors++
            else warnings++
        }
    }
    for (const component of document.components) {
        tally(component.diagnostics)
        for (const prop of Object.values(component.props)) tally(prop.diagnostics)
    }
    return { errors, warnings }
}

async function writeMetadataDocument(outputRoot: string, document: MetadataDocument): Promise<void> {
    const target = path.resolve(outputRoot, metadataFileName)

    let existing: string | undefined
    try {
        existing = await fs.readFile(target, "utf-8")
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
    }

    if (existing !== undefined) {
        let looksGenerated = false
        try {
            const parsed: unknown = JSON.parse(existing)
            looksGenerated = typeof parsed === "object" && parsed !== null && "schemaVersion" in parsed
        } catch {
            looksGenerated = false
        }
        if (!looksGenerated)
            throw new Error(`Refusing to overwrite a file not generated by reactive-forge: ${target}`)
    }

    const content = `${JSON.stringify(document, null, 2)}\n`
    if (existing === content) return

    // Not logged via `logger.info`: `generatedAt` changes on every run, so
    // this file differs on (near) every regeneration even when nothing about
    // the extracted components changed - logging it as an "Updating" line
    // like the wrapper/aggregate files would be noise, not signal, and would
    // break their idempotent-regeneration-produces-no-log-output contract.
    await fs.mkdir(outputRoot, { recursive: true })
    await fs.writeFile(target, content, "utf-8")
}

async function saveFileIfChanged(file: SourceFile, logger: Logger): Promise<void> {
    try {
        if (await fs.readFile(file.getFilePath(), "utf-8") === file.getFullText()) return
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
    }

    logger.info(`Updating ${file.getFilePath()}`)
    await fs.mkdir(path.dirname(file.getFilePath()), { recursive: true })
    await file.save()
}

function isInside(directory: string, file: string): boolean {
    const relative = path.relative(directory, file)
    return relative !== "" && relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)
}

async function assertGeneratedTarget(project: Project, target: string, sourcePaths: Set<string>): Promise<void> {
    if (sourcePaths.has(target)) throw new Error(`Generated file would overwrite component source: ${target}`)

    let existing: string | undefined
    try {
        existing = await fs.readFile(target, "utf-8")
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
    }
    existing ??= project.getSourceFile(target)?.getFullText()
    if (existing !== undefined && !existing.startsWith(generatedMarker))
        throw new Error(`Refusing to overwrite a file not generated by reactive-forge: ${target}`)
}

export interface GenerateConfig {
    outDir: string
    rootDir: string
    baseDir: string
    pathPrefix: string
}

export async function generateFiles(project: Project, components: ComponentData[], { outDir, rootDir, baseDir, pathPrefix }: GenerateConfig, logger: Logger) {
    interface FileRecord {
        sourcePath: string
        targetPath: string
        specifier: string
        filePath: string
        components: ComponentData[]
    }

    const outputRoot = path.resolve(outDir)
    const sourceRoot = path.resolve(rootDir)
    const records = new Map<string, FileRecord>()

    for (const component of components) {
        const sourcePath = path.resolve(component.sourcePath)
        if (!isInside(sourceRoot, sourcePath))
            throw new Error(`Component source is outside rootDir: ${sourcePath}`)

        let record = records.get(sourcePath)
        if (record === undefined) {
            const relativeSource = path.relative(sourceRoot, sourcePath)
            const targetPath = path.resolve(outputRoot, "__reactive_forge_files", `${relativeSource}.ts`)
            if (!isInside(outputRoot, targetPath))
                throw new Error(`Generated file would escape outDir: ${targetPath}`)

            const relativeImport = path.relative(path.dirname(targetPath), sourcePath).replace(/\.(tsx?|jsx?)$/i, "").replace(/\\/g, "/")
            const specifier = relativeImport.startsWith(".") ? relativeImport : `./${relativeImport}`
            const filePath = path.relative(path.resolve(baseDir), sourcePath).replace(/\.(tsx?|jsx?)$/i, "").replace(/\\/g, "/")
            record = { sourcePath, targetPath, specifier, filePath, components: [] }
            records.set(sourcePath, record)
        }
        record.components.push(component)
    }

    const modules = [...records.values()].sort((a, b) => a.sourcePath.localeCompare(b.sourcePath))
    const aggregatePath = path.resolve(outputRoot, "index.ts")
    const sourcePaths = new Set(modules.map(module => module.sourcePath))
    for (const target of [...modules.map(module => module.targetPath), aggregatePath])
        await assertGeneratedTarget(project, target, sourcePaths)

    const outputFiles: SourceFile[] = []
    for (const module of modules) {
        const resultFile = project.createSourceFile(module.targetPath, "", { overwrite: true })
        resultFile.addImportDeclaration({
            moduleSpecifier: "react",
            namedImports: [{ name: "FC", isTypeOnly: true }]
        })
        resultFile.addImportDeclaration({
            moduleSpecifier: "@reactive-forge/schema",
            namedImports: [{ name: "ComponentFileData", isTypeOnly: true }]
        })

        const imports = module.components.map((component, index) => ({ component, localName: `_rf_component_${String(index)}` }))
        for (const { component, localName } of imports) {
            resultFile.addImportDeclaration({
                moduleSpecifier: module.specifier,
                ...(component.isDefault
                    ? { defaultImport: localName }
                    : { namedImports: [{ name: /^[A-Za-z_$][\w$]*$/.test(component.name) ? component.name : JSON.stringify(component.name), alias: localName }] })
            })
        }

        const componentEntries = imports.map(({ component, localName }) => {
            const argsJson = JSON.stringify(new ObjectSchema(component.args).toJson())
            return `\t\t[${JSON.stringify(component.name)}]: {\n\t\t\tcomponent: ${localName} as FC,\n\t\t\targs: ${argsJson}\n\t\t}`
        }).join(",\n")

        resultFile.addStatements(
            `export const __file: ComponentFileData = {\n\tpath: ${JSON.stringify(pathPrefix + module.filePath)},\n\tcomponents: {\n${componentEntries}\n\t}\n}`
        )
        resultFile.formatText()
        resultFile.insertText(0, `${generatedMarker}\n`)
        outputFiles.push(resultFile)
    }

    const aggregateFile = project.createSourceFile(aggregatePath, "", { overwrite: true })
    aggregateFile.addImportDeclaration({
        moduleSpecifier: "@reactive-forge/schema",
        namedImports: [{ name: "ComponentLibraryData", isTypeOnly: true }]
    })

    const libraryFiles = modules.map((module, index) => {
        const relativePath = path.relative(outputRoot, module.targetPath).replace(/\.ts$/, ".js").replace(/\\/g, "/")
        const alias = `_rf_file_${String(index)}`
        aggregateFile.addImportDeclaration({
            moduleSpecifier: `./${relativePath}`,
            namedImports: [{ name: "__file", alias }]
        })
        return alias
    })
    aggregateFile.addStatements(
        `export const components: ComponentLibraryData = {\n\tfiles: [\n${libraryFiles.map(file => `\t\t${file}`).join(",\n")}\n\t]\n}`
    )
    aggregateFile.formatText()
    aggregateFile.insertText(0, `${generatedMarker}\n`)
    outputFiles.push(aggregateFile)

    for (const file of outputFiles) await saveFileIfChanged(file, logger)

    // Additive metadata artifact (docs/metadata-contract.md). Never alters
    // the wrapper/aggregate content or layout generated above.
    const metadataDocument = buildMetadataDocument(components, rootDir)
    await writeMetadataDocument(outputRoot, metadataDocument)

    // Surface diagnostics to whoever is running codegen, without dumping
    // every diagnostic to stdout (metadata.json has the full detail). Only
    // logged when there is something to report, so a clean, unchanged
    // regeneration still produces no log output (matching the wrapper/
    // aggregate files' idempotent-regeneration contract).
    const { errors, warnings } = countDiagnostics(metadataDocument)
    if (errors > 0 || warnings > 0) {
        logger.info(
            `${String(metadataDocument.components.length)} component(s) extracted with ${String(warnings)} warning(s), ${String(errors)} error(s)`,
            errors === 0
        )
    }
}
